### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by prlz77** [batmanlab/Explanation_by_Progressive_Exaggeration#3]
Hi! Nice work! Would you mind to upload the checkpoints for the Young explainer?

Thanks!!

**Comment by sumedhasingla** [comment]
Hi, Thanks for your request. The checkpoint is available at https://osf.io/8k9hx/files/?view_only=d7f65f2979364b2a99e9eebce6ddd087. 
Filename: CelebA-Young-Binary-Explainer-Checkpoint.zip

**Comment by prlz77** [comment]
Hi, I cannot see it!
![image](https://user-images.githubusercontent.com/1070504/92470800-faa0e380-f1a4-11ea-8f9f-e9f4b3669b66.png)

**Comment by prlz77** [comment]
Thanks!
